CREATE TABLE IF NOT EXISTS invest_settlement_rules (
    rule_code VARCHAR(80) PRIMARY KEY,
    asset_types JSON NOT NULL,
    transaction_types JSON NOT NULL,
    ticker_prefixes JSON NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NULL,
    days_offset INT NOT NULL DEFAULT 0,
    calendar_unit ENUM('business_days', 'calendar_days') NOT NULL DEFAULT 'business_days',
    label VARCHAR(180) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO invest_settlement_rules
    (rule_code, asset_types, transaction_types, ticker_prefixes, valid_from, valid_to, days_offset, calendar_unit, label)
VALUES
    ('B3_OPTION_PREMIUM_D1',
     JSON_ARRAY('option_call', 'option_put'),
     JSON_ARRAY('call_sell', 'put_sell', 'call_buy', 'put_buy'),
     NULL,
     '1900-01-01', NULL, 1, 'business_days', 'Opcao - premio D+1 util'),
    ('B3_EQUITY_D3_LEGACY',
     JSON_ARRAY('stock', 'fii', 'etf', 'bdr'),
     JSON_ARRAY('buy', 'sell'),
     NULL,
     '1900-01-01', '2019-05-26', 3, 'business_days', 'Acao/FII - liquidacao D+3 uteis (regra historica)'),
    ('B3_EQUITY_D2',
     JSON_ARRAY('stock', 'fii', 'etf', 'bdr'),
     JSON_ARRAY('buy', 'sell'),
     NULL,
     '2019-05-27', NULL, 2, 'business_days', 'Acao/FII - liquidacao D+2 uteis'),
    ('TESOURO_D1',
     JSON_ARRAY('fixed_income'),
     JSON_ARRAY('buy', 'sell'),
     JSON_ARRAY('TESOURO-', 'TD-', 'LFT-'),
     '1900-01-01', NULL, 1, 'business_days', 'Tesouro/RF - D+1 util'),
    ('CDB_D1',
     JSON_ARRAY('fixed_income'),
     JSON_ARRAY('buy', 'sell'),
     JSON_ARRAY('CDB-'),
     '1900-01-01', NULL, 1, 'business_days', 'CDB - D+1 util'),
    ('FIXED_INCOME_D1',
     JSON_ARRAY('fixed_income'),
     JSON_ARRAY('buy', 'sell'),
     NULL,
     '1900-01-01', NULL, 1, 'business_days', 'Renda fixa - D+1 util'),
    ('SECURITIES_LENDING_NET30',
     JSON_ARRAY('stock', 'fii', 'securities_lending'),
     JSON_ARRAY('securities_lending'),
     NULL,
     '1900-01-01', NULL, 30, 'calendar_days', 'Aluguel/termo - liquidacao D+30 corridos')
ON DUPLICATE KEY UPDATE
    asset_types = VALUES(asset_types),
    transaction_types = VALUES(transaction_types),
    ticker_prefixes = VALUES(ticker_prefixes),
    valid_from = VALUES(valid_from),
    valid_to = VALUES(valid_to),
    days_offset = VALUES(days_offset),
    calendar_unit = VALUES(calendar_unit),
    label = VALUES(label),
    is_active = TRUE;
